{% set name = "rbc" %}
{% set version = "0.9.1" %}
{% set pypi_name = "rbc-project" %}
{% set bundle = "tar.gz" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xnd-project/rbc/archive/refs/tags/v{{ version }}.tar.gz
  sha256: beceee52c18fd55ae2e95f62859034e41558b613a8372b0f45b80c054a26700a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - thriftpy2
    - tblib
    - llvmlite >=0.29
    - numba
    - netifaces
    - six

test:
  requires:
    - pytest
  commands:
    - pytest -sv -r s -k "not test_python_version" --pyargs rbc
  imports:
    - rbc
    - rbc.thrift

about:
  home: https://github.com/xnd-project/rbc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: RBC - Remote Backend Compiler
  description: |
    The aim of the Remote Backend Compiler project is to distribute
    the tasks of a program JIT compilation process to separate
    computer systems using the client-server model. The frontend of
    the compiler runs on the client computer and the backend runs on
    the server computer. The compiler frontend will send the program
    code to compiler backend in LLVM IR form where it will be compiled
    to machine code.
  doc_url: https://rbc.readthedocs.io/
  dev_url: https://github.com/xnd-project/rbc

extra:
  recipe-maintainers:
    - pearu
    - guilhermeleobas
    - tupui
